name: Sync to Gitee

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          # 必须为 0，确保可以推送全部提交历史
          fetch-depth: 0

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GITEE_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan gitee.com >> ~/.ssh/known_hosts

      - name: Set git config
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

      - name: Push to Gitee
        run: |
          git remote add gitee git@gitee.com:jihaoyun/japanese-vocabulary.git
          # 强制推送保证分支完全同步
          git push gitee HEAD:main -f
